# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: SSH to RaspberryPI

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Test Build
    runs-on: ubuntu-latest
    steps:
    - name: SSH into my Raspberry PI
      run: |
        touch github_key && echo ${{ secrets.SSH_KEY }} >> github_key
        ssh -o StrictHostKeyChecking=no -i github_key ali@${{ secrets.ENDPOINT }}
        