# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: SSH to RaspberryPI

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Test Build
    runs-on: ubuntu-latest
    steps:
    - name: Create SSH Key
      run: |
       touch key 
       ls -a
       echo ${{ secrets.SSH_KEY }} > key
    - name: Attempt to SSH into the PI
      run: ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} -i key ali@${{ secrets.ENDPOINT }}
        