name: SSH to RaspberryPI

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: SSH into my PI!
    runs-on: ubuntu-latest
    steps:
    - name: Create SSH Key
      run: 'echo "$SSH_KEY" > key'
      shell: bash
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
    - name: Attempt to SSH into the PI
      run: ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} -i key ${{ secrets.USER }}@${{ secrets.ENDPOINT }}
        