name: SSH to RaspberryPI

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: SSH into my PI!
    runs-on: ubuntu-latest
    steps:
    - name: Create SSH Key
      run: 'echo "$SSH_KEY" > key'
      shell: bash
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
    - name: set permissions
      run: chmod 600 key
    - name: Create .env file and populate it
      run: 'touch .env && echo "$ENV" > .env'
      shell: bash
      env:
        ENV: ${{ secrets.ENV_FILE }}
    - name: Send .env file to PI
      run: scp -o StrictHostKeyChecking=no -i key -P $PORT .env $USER@$ENDPOINT:dev/Mushroom_Bot
      env:
        PORT: ${{ secrets.SSH_PORT }}
        USER: ${{ secrets.USER }}
        ENDPOINT: ${{ secrets.ENDPOINT }}
    - name: SSH & Deploy
      run: |
        ssh -t -o StrictHostKeyChecking=no -p $PORT -i key $USER@$ENDPOINT \
        '
        cd dev/Mushroom_Bot;
        git pull;
        cd Mushroom_Bot;
        npm ci;
        '
      env:
        PORT: ${{ secrets.SSH_PORT }}
        USER: ${{ secrets.USER }}
        ENDPOINT: ${{ secrets.ENDPOINT }}
        