# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: bot build 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: build the bot
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm ci
        touch .env &&  echo $BOT_TOKEN >> .env
        npm run build --if-present
      
  docker:
    name: build and push to DockerHub
    runs-on: ubuntu-latest
    needs: build
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}  
    steps:
        - name: create .env file
          run: touch .env &&  echo $BOT_TOKEN >> .env
        - name: Docker Login
          run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - name: Docker Build
          run: docker build . -t mushroombot:latest
        - name: Docker Push
          run: docker push lordmushroom/mushroombot:latest
