# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: bot build 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: touch .env &&  echo $BOT_TOKEN >> .env
    - run: npm run build --if-present
      
  docker:
    runs-on: ubuntu-latest
    needs: build
    env:
      username:  ${{ secrets.DOCKERHUB_USERNAME }}
      token: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1
          
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
          
        - name: Login to DockerHub
          uses: docker/login-action@v1 
          with:
            username: $username
            password: $token
        - name: Build and push
          id: docker_build
          uses: docker/build-push-action@v2
          with:
            push: true
            tags: user/app:latest
            build-args: |
              arg1=value1
              arg2=value2
        - name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}
